# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpectraMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14SpectraMessage.proto\"C\n\rClientDataMsg\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x61udio_id\x18\x02 \x01(\x02\x12\x0c\n\x04time\x18\x03 \x01(\x02\"5\n\x11ServerResponseMsg\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SpectraMessage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CLIENTDATAMSG']._serialized_start=24
  _globals['_CLIENTDATAMSG']._serialized_end=91
  _globals['_SERVERRESPONSEMSG']._serialized_start=93
  _globals['_SERVERRESPONSEMSG']._serialized_end=146
# @@protoc_insertion_point(module_scope)
